# Generated by Django 5.1.2 on 2024-10-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
                ('current_subtotal_price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
