# Generated by Django 5.1.2 on 2024-10-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_shop_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
